routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/', '\App\Site\Home\Controllers\HomeController@index', function () {
	return view( 'welcome' );
} )->name( 'home' );

Route::get( '/', function () {
	return view( 'home' );
} )->name( 'home' );

Route::get( '/admin', [ 'middleware' => 'admin' ], function () {
	return view( 'admin.dashboard.index' );
} );

Route::group( [ 'prefix' => 'admin', 'namespace' => 'admin', 'middleware' => 'admin' ], function () {
	Route::get( '/urlshortner', 'UrlShortnerController@generate' )->name( 'admin.urlshortner' );
	Route::post( '/urlshortner', 'UrlShortnerController@store' )->name( 'admin.urlshortner' );
	Route::get( '/urlshortner/list', 'UrlShortnerController@show' )->name( 'admin.urlshortner.list' );
	Route::get( '/redirect/{code}', 'UrlShortnerController@redirect' );
} );

Route::group( [ 'prefix' => 'admin', 'middleware' => 'Authorize' ], function () {
	Route::resource( 'users', '\App\Admin\Users\Controllers\UsersController', [ 'as' => 'admin' ] );
	Route::resource( 'permissions', '\App\Admin\Permissions\Controllers\PermissionController', [ 'as' => 'admin' ] );
	Route::resource( 'roles', '\App\Admin\Roles\Controllers\RolesController', [ 'as' => 'admin' ] );
//	Route::resource( 'agencies', '\App\Admin\Agencies\Controllers\AgencieController', [ 'as' => 'admin' ] );
	Route::resource( 'posts', '\App\Admin\Posts\Controllers\PostsController', [ 'as' => 'admin' ] );
	Route::post( 'post/like', '\App\Admin\Posts\Controllers\PostsController@like', [ 'as' => 'admin' ] )->name( 'admin.post.like' );
//	Route::get( '/agencies/{id}/tour', '\App\Admin\Agencies\Controllers\AgencieController@toure', [ 'as' => 'admin' ] )->name( 'create.tour' );
	Route::resource( 'tours', '\App\Admin\Tours\Controllers\ToursController', [ 'as' => 'admin' ] );
	Route::get( '/', '\App\Admin\Dashboard\Controllers\DashboardController@index' )->name( 'admin.general.index' );
	Route::resource( '/products', '\App\Admin\Products\Controllers\ProductsController', [ 'as' => 'admin' ] );
	Route::post( '/products/get-attributes', '\App\Admin\Products\Controllers\ProductsController@getAttributes' );
	Route::post( '/products/get-options', '\App\Admin\products\Controllers\productsController@getOptions' );
	Route::resource( '/categories', '\App\Admin\Categories\Controllers\CategoriesController', [ 'as' => 'admin' ] );
	Route::resource( '/attributes', '\App\Admin\Attributes\Controllers\AttributesController', [ 'as' => 'admin' ] );
	Route::resource( '/options', '\App\Admin\Options\Controller\OptionsController', [ 'as' => 'admin' ] );
	Route::resource( '/ads', '\App\admin\Ads\Controllers\AdsController', [ 'as' => 'admin' ] );
	Route::post( '/ads/get-attributes', '\App\Admin\Ads\Controllers\AdsController@getAttributes' );
	Route::get( '/ads/waiting ', '\App\admin\Ads\Controllers\AdsController@waiting ', [ 'as' => 'admin' ] );
} );


Route::get( 'tags/{slug}', 'TagsController@index' )->name( 'tags.index' );

Route::group( [ 'prefix' => 'dashboard', 'namespace' => 'dashboard', 'middleware' => 'Authorize' ], function () {
	Route::get( '/', '\App\Admin\Tags\Controllers\IndexController@index' )->name( 'dashboard.general.index' );
} );

// Authentication Routes...
Route::get( 'login', '\App\General\Auth\Controllers\LoginController@showLoginForm' )->name( 'login' );
Route::post( 'login', '\App\General\Auth\Controllers\LoginController@login' );
Route::post( 'logout', '\App\General\Auth\Controllers\LoginController@logout' )->name( 'logout' );

// Registration Routes...
Route::get( 'register', '\App\General\Auth\Controllers\RegisterController@showRegistrationForm' )->name( 'register' );
Route::post( 'register', '\App\General\Auth\Controllers\RegisterController@register' );

// Password Reset Routes...
Route::get( 'password/reset', '\App\General\Auth\Controllers\ForgotPasswordController@showLinkRequestForm' );
Route::post( 'password/email', '\App\General\Auth\Controllers\ForgotPasswordController@sendResetLinkEmail' );
Route::get( 'password/reset/{token}', '\App\General\Auth\Controllers\ResetPasswordController@showResetForm' );
Route::post( 'password/reset', '\App\General\Auth\Controllers\ResetPasswordController@reset' );

Route::resource( '/products', '\App\Site\Products\Controllers\ProductsController' );
Route::post( '/product/{id}/comment', '\App\Site\Products\Controllers\ProductsController@comment' )->name( 'site.product.comment' );
Route::get( '/crawler', '\App\Site\Products\Controllers\CrawlerController@index' );

Route::get( '/test', 'TestController@index' );

Route::get( '/news', '\App\Site\Posts\Controllers\PostsController@index' );

Route::post( '/news/{id}/comment', '\App\Site\Posts\Controllers\PostsController@comment' )->name( 'site.post.comment' );
//
Route::get( '/news/{id}-{slug}', '\App\Site\Posts\Controllers\PostsController@show' )->name( 'news.show' );
Route::get( '/news/{id}-', '\App\Site\Posts\Controllers\PostsController@show' );
Route::get( '/news/{id}', '\App\Site\Posts\Controllers\PostsController@show' );
//
Route::post( '/comment', [
	'as'   => 'site.comment',
	'uses' => '\App\Site\Comment\Controllers\CommentsController@store'
] );

Route::resource( '/register', '\App\Site\Register\Controllers\RegisterController', [ 'as' => 'site' ] );



Route::group( [ 'prefix' => 'profile', 'middleware' => 'Authorize' ], function () {
	Route::resource( '/', '\App\Profile\Controllers\ProfileController', [ 'as' => 'site' ] );
	Route::resource( '/course', '\App\Profile\Courses\Controllers\CourseController', [ 'as' => 'site' ] );
} );


//Route::get( '/profile', function () {
//
//		return view( 'profile.dashboard.index');
//});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{

//	protected $fillable = ['name'];
	protected $guarded = ['id'];
	public function users() {
//		return $this->belongsToMany(User::class,'user_roles','role_id','user_id');
		return $this->belongsToMany(User::class);
	}

	public function permissions() {
		return $this->belongsToMany(Permission::class);
	}


}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Admin\Roles\Forms\RoleForm;
use App\Http\Requests\RoleRequest;
use App\Role;
use Kris\LaravelFormBuilder\FormBuilderTrait;
use RealRashid\SweetAlert\Facades\Alert;


class RolesController extends Controller {


	use FormBuilderTrait;

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {

		Alert::alert('Title', 'Message', 'Type');

		$roles = Role::all();

		return view( 'admin.roles.index', compact( 'roles' ) );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

		$form = $this->form( RoleForm::class, [
			'method' => 'POST',
			'url'    => route( 'admin.roles.store' )
		] );

		return view( 'admin.roles.create', compact( 'form' ) );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( RoleRequest $request ) {

		$permission_ids = $request->input( 'permissions_ids', [] );

		$role = Role::create( [
			'name' => $request['name'],
		] );

		$role->permissions()->attach( $permission_ids );

		alert()->success('Role Created', 'Successfully');

		return redirect()->route( 'admin.roles.edit', [ 'id' => $role->id ] );

	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function show( $id ) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( $id ) {

		$role = Role::findOrFail( $id );

		$model = $role->toArray();

		$model['permissions_ids'] = $role->permissions->pluck( 'id' )->toArray();

		$form = \FormBuilder::create( RoleForm::class, [
			'method' => 'PUT',
			'url'    => route( 'admin.roles.update', [ 'id' => $role->id ] ),
			'model'  => $model
		] );

		return view( 'admin.roles.create', compact( 'form' ) );

	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( RoleRequest $request, Role $role ) {

		$permission_ids = $request['permissions_ids'];
		unset( $request['permissions_ids'] );

		$role->update( $request->all() );

		$role->permissions()->sync( $permission_ids );

		return redirect()->back();

	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( $id ) {
		//
	}
}

resources/views/admin/roles/create.blade.php
@extends('layout.admin')



@section('content')


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
            @include('admin.Partials.alert')

            <!-- general form elements -->
                <div class="box box-primary">

                    {!! form($form) !!}

                    @include('sweetalert::alert')



                </div>
            </div>
        </div>
    </section>
    <!-- /.box -->


@endsection

resources/views/admin/roles/index.blade.php
@extends('layout.admin')

@include('sweetalert::alert')


@section('content')



    <section class="content">
        <div class="row">
            <div class="col-xs-9">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">لیست تور ها</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>شناسه</th>
                                <th>نقش</th>
                                <th style="text-align: center">ادیت</th>
                            </tr>
                            </thead>
                            @foreach($roles as $role)

                                <tr>
                                    <td > {{  $role->id }} </td>
                                    <td > {{  $role->name }} </td>


                                <td style="text-align: center">
                                    <a href="{{ route('admin.roles.edit',$role->id) }}">
                                        <li class="glyphicon glyphicon-edit"></li>
                                    </a>
                                    {{--<a href="{{  route('admin.users.destroy',$role->id)  }}">--}}
                                        {{--<li class="glyphicon glyphicon-trash"></li>--}}
                                    {{--</a>--}}
                                </td>

                                </tr>

                            @endforeach




                            <tfoot>
                            <tr>
                                <th>شناسه</th>
                                <th>نام تور</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->


                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

@endsection